version: 2
mkdocs:
  configuration: mkdocs.yml
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install --upgrade pip
      - pip install mkdocs mkdocs-material